# Site
repository: sproogen/resume-theme
favicon: images/ico.ico

# Personal info
name: Russell DeSousa
title: Robotics Engineering Student
email: brdesousa@wpi.edu
website: https://github.com/RussellDeso

# Social links
#twitter_username: facespics
github_username:  RussellDeso
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: russelldeso
linkedin_username: RussellDesousa
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/pfpcrop.png
about_content: | # this will include new lines to allow paragraphs
  My name is Russell and I'm a self-proclaimed robotics engineering nerd with experience in all major aspects of robotics. With years worth of working in teams to solve engineering problems, tackling competitions, and designing products, I am highly comfortable working in teams from small to large.

  I am most skilled in <mark>Mechanical Design</mark>, <mark>Product Design</mark>, and more recently, <mark>Programming</mark>. I dabble in areas outside of these, and I am interested in learning all there is to know about my field.

# Education Section
# educaton_title: Education

# Experience Section
# experience_title: Experience

# Projects Section
# projects_title: Projects

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  In addition to my interest in robotics and engineering as a whole, I'm also interested in the following:
   - Photography
   - Graphic Design
   - Machine shop work

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
