# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Russell DeSousa
title: Robotics Engineering Student
email: brdesousa@wpi.edu
website: https://github.com/RussellDeso

# Social links
#twitter_username: facespics
github_username:  RussellDeso
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: russelldeso
linkedin_username: RussellDesousa
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Russell and I'm a self-proclaimed robotics engineering nerd with experience in all major aspects of robotics. With years worth of working in teams to solve engineering problems, tackling competitions, and designing products, I am highly comfortable working in teams from small to large.

  I am most skilled in <mark>Mechanical Design</mark>, <mark>Product Design</mark>, and more recently, <mark>Programming</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
